hash-format = "sha256"

[[files]]
file = "config/aether-common.toml"
hash = "becf75f2578b0a788872fe177e20e8e33371bf340567ef5ba6302eb049c9e3f5"

[[files]]
file = "config/alexscaves-general.toml"
hash = "85ec70d0bf8de038c940afb6c9feb6e887cfbc8fd8d86352a8b2ad12bc070aca"

[[files]]
file = "config/alexscaves_biome_generation/abyssal_chasm.json"
hash = "5acb1b3a5b688e23eb6708435834276b46f1d4b7b2c3869a959cb40415b1d73f"

[[files]]
file = "config/alexscaves_biome_generation/forlorn_hollows.json"
hash = "25151d28ef7df78cbf1f8887bba0134610141ff420ff447b230a1c5a30319ffb"

[[files]]
file = "config/alexscaves_biome_generation/magnetic_caves.json"
hash = "91b7b5f7d6bdac7d0dab8ba382f29e8791477be1f58065dc2297d312b84bc522"

[[files]]
file = "config/alexscaves_biome_generation/primordial_caves.json"
hash = "fffb03b1c2980ecef9322d0ff775d43a5f577fd976979dbd17b0f42cd67b6f25"

[[files]]
file = "config/alexscaves_biome_generation/toxic_caves.json"
hash = "c5d817ce4c9d4bda183827f4fe8456823e80c1ea1b4372dd3dcf58d0bc1fe02f"

[[files]]
file = "config/atlantis-common.toml"
hash = "b56416a57ddc1b93e369b71a51464d1503f935db9b69c9079953e495c50917cf"

[[files]]
file = "config/distantworlds-common.toml"
hash = "2d1898653714df2d91f0b14c92ef38a19863226899e5727114b90559d45ad58f"

[[files]]
file = "config/iceandfire-common.toml"
hash = "4e686e3616fc1885ce4380e95fe8c9d32be13536693da638e27b091372c0777b"

[[files]]
file = "config/philips-ruins-common-configs.toml"
hash = "59c9c58d632cc807ccc4d1c11d1144acdb688cacba0ffab2836d617106c44cce"

[[files]]
file = "config/waystones-common.toml"
hash = "424d0c843716670a48008cba7283da677f31f0fe756e08c66e475153d70d151d"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "7bcaa909613c955d99e6982018a780622dfc91c6dd462791f5e67c17599d5a3f"

[[files]]
file = "dimensions.txt"
hash = "42206bb95fc9f9e120c5e1bd5a8bbec20257c60cda4e76fc14f021a5b1c5b100"

[[files]]
file = "mods/aether.pw.toml"
hash = "801f5f50e8f6022f58e6ff62198958a81924ef6058f52ae6d115952311c5ac6d"
metafile = true

[[files]]
file = "mods/alexs-caves.pw.toml"
hash = "ec436a1f3378f8bd08ccd02e0ee74c441ff51d73bb62d446f6123eb2d6ebed6b"
metafile = true

[[files]]
file = "mods/alexs-mobs-extra-music.pw.toml"
hash = "d3cbc7d56864473e0dae982a636fce65946684b0d41fba2d8adf13b1afb1afda"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "c7ef8f8629620ae3d9d2da71aaf440624c40157a80c0eda4298c0aa60b7c76c0"
metafile = true

[[files]]
file = "mods/alexscaves-torpedoes.pw.toml"
hash = "926e2f629cd4c93d6e12d76c46ff2fa746f648eb8cb6eef635bd241a9d7e5195"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "fa34a3117af7f8ed553ec563a7c90c1d6462184c7df5b837c831cb482c6ae582"
metafile = true

[[files]]
file = "mods/atlantis.pw.toml"
hash = "d56ad3592da32c6407d7442a167861073d44f25e536d7a726d697213c88d6859"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "55c3c0b90712f84b1936ef69bbc1937bedd2e499b65003e0f22f00ad744a885b"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "38e1841f79d0fc489e9a094fa6611b8e890be8d742480b800467a3df873b221c"
metafile = true

[[files]]
file = "mods/bens-sharks.pw.toml"
hash = "248cead13effb47510dd6dc670de6c16fdc436f1558aafa5c54f13fbcfeb6a90"
metafile = true

[[files]]
file = "mods/better-forests.pw.toml"
hash = "e9ae23bd6e5c2f25bef21bc7379c9cf5e7a99bc0b233f5f2f1ba31200ccb8d2d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "ca52b58cf0540bcec5d8b0318cddb371683b6f3f87ad9b925ff600ddd330f461"
metafile = true

[[files]]
file = "mods/blooming-biosphere.pw.toml"
hash = "9c30c5f1b5d38e8f4cc8a9eedda10405f344c4148770261f5775374049cd9df1"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "eaa144428b42dedd12beea31db366ca686a621c9945d45a35494dca25846fc63"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "a388f4afe890e268a739cf598b68859ca3d86506a3fa3e46c17e4aa63debd309"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "e06b4f6a4a5fa7982439f57ca5015b616c606789d9deef0ddb78838b85306fed"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "38cf4a76862812fefc9b1ae0b8fac02b3f706716f3228eb859b511950273e791"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "a704bc3997d75ffc2cac8311ef97f6336fcae75f6c82242d8a36fc15a2641c56"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "2a50d21837bba88e3c9490c6bb8e0a9b44b052645d5c1481b48a060439c20a3c"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "9261b71e382b07771083e0998e2a8e6997a874e8384fd0e1020774ae8c64baba"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
hash = "f07ab6e7174e5381c34281c5516936c65328f184c8edb55eda2a65d2b18d2d22"
metafile = true

[[files]]
file = "mods/ctov-irons-spells-n-spellbooks-compat.pw.toml"
hash = "d87155118199bba53181b3f293aa1274e1b47212ea395125becc171113c0129a"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "69dd03aa24b8172ed8644a73dd477521afd7ca6841b77320f0d13534968aad3a"
metafile = true

[[files]]
file = "mods/damagenumbers.pw.toml"
hash = "ee3593e70420fd691ede6f65bd0989402b18b48ebe41280229a4b8c1cc3cb083"
metafile = true

[[files]]
file = "mods/dcintegration.pw.toml"
hash = "ec5b452599201804f40e6a9f4549849065b8428d5b046bd0638f9897e1e4b72c"
metafile = true

[[files]]
file = "mods/distant-worlds.pw.toml"
hash = "419bcc80436f50a61370d1142f64623250fe9dbcccaabd4d35edf2dfdca16214"
metafile = true

[[files]]
file = "mods/dungeons-enhanced.pw.toml"
hash = "7a36954588c8e552381bcec868e9d83a85f088d939fbbee0b5df82943d039f04"
metafile = true

[[files]]
file = "mods/dynamic-lights.pw.toml"
hash = "be04da0004ea86c126254940907e6767082778405141c15c170fb6c7fffebd37"
metafile = true

[[files]]
file = "mods/dynamic-music-updated.pw.toml"
hash = "0605000880c10019e16075a1615490ebe0f5a71038960b14f779e82607342164"
metafile = true

[[files]]
file = "mods/easier-sleeping.pw.toml"
hash = "fc4c3283c4f755eb185edf39a99af0114f0b165552e67f0ac1b83ada520c0081"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5d689fdd1fe74d0fbbe67af6ae186a49ac3efeb1d00341a8c7c6ab663829b5fd"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "930f3c6ba869160e03c602b88bdb07cc1e994f8dab353f8df084c076219d701c"
metafile = true

[[files]]
file = "mods/fantasy-metals.pw.toml"
hash = "4735068b0ec7da7e41a864cc2faebf3e07759265c8ce0ba1958e0d96008650bb"
metafile = true

[[files]]
file = "mods/fapdos-nether-mobs-recrafted.pw.toml"
hash = "ea4ad4f1cce7fa52097b85173d09359e62f730e322a3b3426c5ade01d4c24446"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4a73f04a8986129d79ea4f283a0a33ce51af17079b6efa23596af5bc685e1c1e"
metafile = true

[[files]]
file = "mods/fog-looks-modern-now.pw.toml"
hash = "b31deb48d2140594addc96b1dcd18fea01509d5ce9581290b9dee40627696426"
metafile = true

[[files]]
file = "mods/formations-nether.pw.toml"
hash = "77944fbff816ce24485a03fec6dca329487967d57a08b00ab43ba8b33d58f1aa"
metafile = true

[[files]]
file = "mods/formations-overworld.pw.toml"
hash = "23d853c78443660212c618f0c4237346d8e7471bd35e5a8f90105553757e3eca"
metafile = true

[[files]]
file = "mods/formations.pw.toml"
hash = "28684cfa77b928dc7626d5e7149a78a3b7ec6b6a69102774224cdcbab900284e"
metafile = true

[[files]]
file = "mods/fps-reducer.pw.toml"
hash = "148adc903fe1409402b123101158cfb84054ba5b4e4826e017cb3d509d8fb9b2"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "e4d08b3c4858f3ad79ae779eb8be71534883e88b95fd59462ecce7f59cd72184"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "fd554c207bd89ccba53ef4db8f206d804cc6d6ec766bbdddc707af2d126b9cd7"
metafile = true

[[files]]
file = "mods/hearths.pw.toml"
hash = "9b616f9d8b500033413086441f2b4c7dfee30645296accbcc2feaa72aa04392d"
metafile = true

[[files]]
file = "mods/hopo-better-mineshaft.pw.toml"
hash = "1a06a46a1f78e713e070beb02d0ff9a4cad3365898a4dadda6deb3eb587b7878"
metafile = true

[[files]]
file = "mods/hopo-better-ruined-portals.pw.toml"
hash = "eb82ce8edafc56ce63c1f91b51903c7d86927135c0ca8d64eedac1f9aba37820"
metafile = true

[[files]]
file = "mods/hopo-better-underwater-ruins.pw.toml"
hash = "d29a7b417432dd8ea0e0c1535ca6ec26e75cad58eec96c80037dbf24ed1634c1"
metafile = true

[[files]]
file = "mods/ice-and-fire-dragons.pw.toml"
hash = "5cddb71ac06974f13689c1d9b0ff4d9ba0edfbb12ce974228f3383a77228a596"
metafile = true

[[files]]
file = "mods/ice-and-fire-spellbooks.pw.toml"
hash = "67e4fa2d83b0afa6624e4d3dde3455c3766fd0980c3a4a309d087bf2a2248a33"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "b26d43f4ee899128880f84a4bda5caf2d4a619115816556a616430b5c8928406"
metafile = true

[[files]]
file = "mods/irons-rpg-tweaks.pw.toml"
hash = "41da136e933b2119588099aa9bbd6618ad840ac371875c22a1e391e774065b6d"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "a5fd2e6d186ccf84f7b54efa4887d948c41dd08d573c5cc9baa80c821d3525a7"
metafile = true

[[files]]
file = "mods/itemphysic-lite.pw.toml"
hash = "077fd4e83502f59ea6fa53bd46b3d3112e905f5b272b63e93f2d2c1e1196a917"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "b4d8f52ac3e7bee8de9dff18d5dda00b23ae3a118778ab374e036ffdffd13f20"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "e93f24623fe48bd7eee6e54e80c223ce71e639e210372124b8f22dd6b72924cc"
metafile = true

[[files]]
file = "mods/kleiders-custom-renderer-api.pw.toml"
hash = "008077a021bdac4f7bdbaa7e85dbdf67969215ebf8bcfc979ec1c711910b4357"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "cd74d3de1cd246e509142cbee67c94b652aecb49927bf3c30f84081c54d41f5c"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "eab12c7fddf20f293b8726f7553d2c0c0b6c578a2ba03ddf59ae40f6e684e2ce"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "5313dd0c3ee565ae28c29e659db5937c65508220873dce58a70491aab76efb52"
metafile = true

[[files]]
file = "mods/more-metals.pw.toml"
hash = "75ea00008ca829090781841954d775e952c5e7d05c979bf124fe3b7a0d571258"
metafile = true

[[files]]
file = "mods/nether-depths-upgrade.pw.toml"
hash = "9b46a1f9cf406f1b1dd64d5db3219bbe0490fba11ddb36ab7fd8b9f29e28f21b"
metafile = true

[[files]]
file = "mods/nether-dungeons.pw.toml"
hash = "972e94424dfabf10c75566e4113a04369c98d0ccc75de228fb89133f814b76e6"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9a3c80bf6eee8234001d2a1602b3e123ac5706af051902e40f24abe317b86e50"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "967412dd78791d3c8ed00470ac9dd9473d0d03fdf78d04a9a004ea79bfcbde70"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "81d06b76e9cb7cb1e0c8f69724055a24ec75291c67d32a5740bd8bafd6ba7940"
metafile = true

[[files]]
file = "mods/ore-harvester.pw.toml"
hash = "ebbcff06a3b5caa6b5826e513a18f6f5d2687baeca894cd75c5a05c8235427b7"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "4d0b66ba4cb3c2965bf961d4bb991babb6a60f8a20709d1e295ed7fc8b6d8929"
metafile = true

[[files]]
file = "mods/philips-ruins.pw.toml"
hash = "4cd04e0a9092ab29fe2c6ec9a6ac92f20c7e520d89ab4eade9e5ac22fb6890cc"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "30484a8787dd30e579c7098b77d0c1d243044c7458828b87d8c81c92001717fa"
metafile = true

[[files]]
file = "mods/prometheusexporter.pw.toml"
hash = "04bd22de632e7f671f7416ead44fde0988509fd55f5c12fd44f55da67ecb5e5e"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "f28e1481c14143758e65c2ae472f644793228ef91f5fbc041909b4c25c3525c0"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "35905f57cdb21a2aaa26345f2fabe3137ee2db6ee3bb2149cea206611b11ef69"
metafile = true

[[files]]
file = "mods/simplest-copper-gear.pw.toml"
hash = "a1821299772cfa3ac268460db7a67db99023aee61240b178e53d2adc6b0bf16d"
metafile = true

[[files]]
file = "mods/sky-lands.pw.toml"
hash = "82ce276d50b08471b1358506034518d3910dd48193e08a8274fd40156fef04ad"
metafile = true

[[files]]
file = "mods/small-ships.pw.toml"
hash = "bf4028cc11d1b8710a922f42233ad37fae16a39ad2c0df4753c0f06416238d83"
metafile = true

[[files]]
file = "mods/spells-gone-wrong.pw.toml"
hash = "44e574f67af52bda95752056e96cf1bcd50145d4efdcf0d2be520102e39f299f"
metafile = true

[[files]]
file = "mods/spiritual-come-back-(scb).pw.toml"
hash = "588fef0210eb4f6301a29a9cdd4f25f68abaafcd15305411a5a0bc85c0ca6a39"
metafile = true

[[files]]
file = "mods/structure-gel-api.pw.toml"
hash = "f9966c3e2ba050306b8c96f610ed705931cc48fedca54fb4270af875aa54dff3"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "3c024c63263f4f879d604a01fe13f81119565907f0883f2d7eb53a2cc413546c"
metafile = true

[[files]]
file = "mods/totw-modded.pw.toml"
hash = "cc4d196949d893071f261e939501ca8c7a79ba8ced3d790ce98d25e4f207bca3"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "0328dcee3fced9edb7fe463b35624381fc94e09f6303a7cb1cdccb26747a130c"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "5dc49fed1045ca205ac2a750bb34e3e2526bf9577498b4013fc79efd67e6dd89"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "05bf4c054b1346db1696d76ebbbea07fc30668251a3c78905a98b3045df4dbf7"
metafile = true

[[files]]
file = "mods/weapon-leveling.pw.toml"
hash = "dc305fa586c81a37d842e19166bc656773e3d75d7ca25cd6954955142ae7d59f"
metafile = true

[[files]]
file = "mods/wfs-cave-overhaul.pw.toml"
hash = "8997d41c5416eeac47ea1b59b96799b94fa037ce53cb4649a4e1ade1681c0032"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "a4f51b0ae9d618e46d8d1c0b08a32d1639aa6338a8400ec14d61dbca1af272af"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "c1918df9e7d093988f06d5443ee9516f447054754335c5426d0516286c25c876"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "896b09e7166d70f08e089862ad5eb8dbc8cfed02608f2c478587dbea191aadf2"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "c2e3390b5330508e73c0e0d42067dcbdb1137e73ce7ec4324288fd3b7ed2d50d"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "647dc25daba3bac1f6e93e3abedaa80d00c83812595e0cf42df5ae966058e84f"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "7e9f9d03e9777945478efb8eedc7e3b23d8986c6f3275cba4e3d6ffb65adb13e"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "2b4c452b8e077743406460087ecba4a8e7b93d581308c4879dda8a35ed6e86c4"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "4143741c21217772c5f568cef36ec16861f9895d193f5eff3c674a6032fac4f1"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "9ad77d663f0a287c2a902d71ccf7221f4ab49a29946743432e4ccb7506e86c21"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "584b719bb17c63ca4bb1432f45af46a17e1bce6307565f13b9c0298bb80f6945"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "7deb34098e5722d3b024231e937c66984e5874f653f0cfc95482f22bbc18f4d4"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "d92d38a261d5c8449b33c114ba3391567c5aca8853301928746de2386348b50b"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "eaa9678b7f6aee59266500c8d3fec01f7bce7c8fe5a0517747e9676cb0d2f1fc"
metafile = true

[[files]]
file = "mods/yungs-menu-tweaks.pw.toml"
hash = "5b5fdfaf8e757e4f54e621aca1c52f5d8c90c7be3bc78c2978173326f5c02bf5"
metafile = true
