hash-format = "sha256"

[[files]]
file = "mods/ae2.pw.toml"
hash = "58f9b55c0998e0df2eaeea259e1bd181a3c4eb93f32824bdac565cec66f94880"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "bedc5fd207a9959c72565f0131b65a8eec71dcdef3e83f6c4556f81e7292326a"
metafile = true

[[files]]
file = "mods/aquamirae.pw.toml"
hash = "ea42747450c6c385925895e98de7c1347c6e24b034bbaee198d5dfda4bb8eb1d"
metafile = true

[[files]]
file = "mods/beautified-chat-client.pw.toml"
hash = "781f3a99d5e8a69b05698ecb8540caa250e332affde988d138bec7257a900882"
metafile = true

[[files]]
file = "mods/better-archeology.pw.toml"
hash = "4ce8cd02fd6db139f101a9643068702bcc77dab491454e73a3bcf0638710a62a"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "39c1c613510610ba17f1c40af55cbcf33cde14466f2f6ef9ab102fe67bf6cec5"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "7721e78d990cc15c02f1a03cd6d7652ea995b271a3d19a6ae44829b4c69acbf0"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "c176a0f84b0c3c03423e68b988cd43f51a6b1cf13a844574b19e003324533da0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b6348f94ec939f563285dc96683e61da8fc17ab2f2897be2751fa24789513691"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "7df8b9795c51643f31cba87ecaea0db96cf2edae97f09e1d37f85fba82adceb8"
metafile = true

[[files]]
file = "mods/create-fabric-sodium-fix.pw.toml"
hash = "738234a75b69eadde29b6ebda5f0be28a3ac7f583d31f9a9a62febd4e784c3b7"
metafile = true

[[files]]
file = "mods/create-garnished.pw.toml"
hash = "cb9fdb09d560c15845c4f74f39452afcc5c85c8b11c862079a9f01161e96db68"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "7315f8be08ca7069ed72746d12e36e81b7959136d0b0c789e16cdb5db8a87dfe"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "2995bd6fc4d6cfb207625005e7392fc09aefe226a0441cceca6687dfc1883ad6"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
hash = "f0323722f66e5b288875294fb083404998a5891751e9460c1f4a4f44626bcc2c"
metafile = true

[[files]]
file = "mods/create-track-map.pw.toml"
hash = "93adce5ea0a86dc042dfac4ae7f2f7068e159b57426cd4de2c7db35615f74e28"
metafile = true

[[files]]
file = "mods/create-utilities.pw.toml"
hash = "ee71f054700c411558f83d0651c54ce872e30395bf3fed28f769ea125a80415b"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "c56ae338249990a510c4479047c812cf320e5b3cf92833876fb43d846dc602ad"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "6e6ee1bf66d6977728d3bf5404338c87a0a4ad5260833efcd912aaaca776cf8f"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "9884c9af4ba83cbdf8bc6b102a257068566641a17d2c6dde63dcf41d0dd0603e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "33f865a014f3acf2c1f2c452bfe7ba1a864acad178322a6eab3759c7e63c9654"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "2b9b5a34a6f3cb5796b4e9996fe1da41d7b063b2727743aeed6c8d350d7cdbb6"
metafile = true

[[files]]
file = "mods/extended-cogwheels.pw.toml"
hash = "e5a66f936624909d847060c6aee2cded1300934c5ad1396db173275293dfbf86"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "119c2437e208c88b2c86cb5dbad22ac12ae310282e6691dfc86aade596f6f70c"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "c20c449b77e7e40bf6b5308d63223b634eb6a857bf3b22d31e9c41f6e03d399b"
metafile = true

[[files]]
file = "mods/fabricexporter.pw.toml"
hash = "4637aea36cfa56c6456981c710535cdde86f1006fb4c1ba239fbc759b782cd88"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "9e2a974e3b686e1e0370722b2e59497c99baeff1a844ff30131a22818d17f3b7"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "39a6a39433b1b104bfafafcd60a8171f866daa2ebefffd64df822d0e69288e3a"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "129bb8b135edc60038f021b693f5b88a0067b722f326e0d6067112243774289b"
metafile = true

[[files]]
file = "mods/galosphere.pw.toml"
hash = "d621a0fd3532a74353d363eff7c8919bf3c3033d759f810c27677eda3bfc0109"
metafile = true

[[files]]
file = "mods/gui-clock.pw.toml"
hash = "e588c87cac0431accdf0a94870173b41bf2ad8f6cf8af05ed57bbd160a64f49d"
metafile = true

[[files]]
file = "mods/gui-compass.pw.toml"
hash = "8254a82f567e6695d4a4960faea27221d2daf284533d283ced5516be71b07dab"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "7e9f6a5b564e4fbe92bff784eb13a2565eb5a631ed452cf9b8748e73935ae8b2"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "bab5dd5660ba526d663b545bc9047176572d091b0657cf27d884e45d66d4b57f"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "0c5e71addef34c8dcd1c81dfc2ad851a3e274b9d8d3a7d388e1113d4139bf8d8"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
hash = "f150264c0991c3faa578a2669ccfb3964850f6d759acc84dad0b545abd9c8915"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "559a46acee6bd5368fac543cb90902a7eb692426329d1041af790d8a22167154"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "71ef7cc16632c0039fe194183b5885968c6d740aaa67a58000653ae0cb40b882"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "d7c03a9a61a81693732b6ae275f63ee63aa97def2e511be48b740e03c4f34a17"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "8e42842f48b3227733bafced612212eee2298f567ca599ac6a55b9878ae661da"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "e0e8c3e60bac3df37dd6d4ea9d1a5ea91807727ef797b557996d4e4062219d90"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4cd171d3f5f3e1d2948cb1b0062e742a5e85110c9e9a668f9aed5b0cebcb9c97"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "be1f88824f7ceb008ce38ae763a93921db0c27db68577fdb16c29c6a085ec1f3"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7ca62a9da5c2ec9f0a8bed5394021c959e90077db16b313be44f4c8736f7fbf5"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "9e09f07e73ff32e66e284584c72aeda18b81c4c3706e1be38352dbf072126102"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
hash = "5b96aa24048b1cea2e05b91954a25579f41c83c7008afd5c48426b579664288a"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "8ecb202cbaf851233c9b3ff1541f8c70af8334779d59e8046450d6bcd62edc67"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "44b0a2294e1693230308e53b529d671a0303e94b623ba2c2650cdf5760a5a335"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9a927c3e0830ba32e1b8a2e543597781724462595b8cce58f676962b442bb52b"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "96e3771cd09bb4a808d1c1fcb5a050efdc2ffb4efe7b584407ed54c46c0388d9"
metafile = true

[[files]]
file = "mods/squaremap.pw.toml"
hash = "76e4ea239bb4f733b8e92ef2086f5b303e7c15ea909d73152873189dc6da003f"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "218f67d6bcaae849582618cd3e5eb1d4cac0fd6045115f64340620300e160c11"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "d4999aa4a0af3e06221075e4cbf62a8ffdc50537353d494ac40dd73f12bc173c"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "c7b5cc4b23192c970f0aa018e1e5e801a56c3ec2149e87eb30e4d57fa624e2ba"
metafile = true

[[files]]
file = "mods/travelers-titles.pw.toml"
hash = "df6c42195656610837ff05462ac37bb40da04a18de198333769030c562cbfe2d"
metafile = true

[[files]]
file = "mods/your-items-are-safe.pw.toml"
hash = "19e818a14117161f8a662c258160b28fc5362d2bae308d4abde520e5244b6fc7"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "b9ffba892e9f541bbffc0fc9dc4360732e9edeb7d2d4560191fc08e457c9d372"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "5ba962b883a36141ce3e505486d07fd30e49412fbcf8b523a81e3bb1b59bb5ba"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "58de55cfb9a33cb71eb7a50a55d6fdd9cc970fd866e603ab5373c9c3087a6d84"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "6253563e28616a16656b12762f897d6007ab19d27e7330030bf9c5af65e3941b"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "2bb58b3921466f6f40b48830415c2e8b6bdacd3b126706ff141014004dad815f"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "bf6e15464cc97754591cb7265ac9402085813c06917f76d99cd79abc61ae5181"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "75f4440f2f2b64dd203612bcbf61951e11c7bb9985ea5bf582736c9adda63c90"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "717541277779ecae1980c5c62d1ad098c20d41a91e7d14927b86582e7e0914b1"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "f683e330873db2c19856790cf2b4b226eecbb44d42c4700b32caab671b2c21f4"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "faffa81c972ce07df81b794c9e52c32b5111b73081eb64140fa01e9db239e409"
metafile = true

[[files]]
file = "mods/yungs-menu-tweaks.pw.toml"
hash = "b92eff4c9b9ddfa65f75fcada278e9782ba9c773e0fb9f690b6ad4cec4c28bd0"
metafile = true
