name = "Money Guys 5 Revival"
author = "Piousp"
version = "2024.06.01"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa3fa7610a85a9776c3c58fe70b0d89270058adcc88c8d13281cda496bfe06fd"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
