
[AutoTools]
	#AutoTools will always be active and try to get you the best tool. Can be toggled with the set key.
	toggle = false
	#Disables AutoTools in creative if toggle is enabled
	disableCreative = true
	#Keeps the selected slot when swapping to a new tool instead of using the vanilla mechanics
	keepSlot = false
	#utoTools will prefer the tool already in your hotbar if multiple tools have the same mining speed, regardless their durability
	preferHotBarTool = true
	#AutoTools will prefer the tool with the lower durability, instead of the higher one, if they have the same mining speed
	preferLowDurability = false
	#Autotools will try to always get a tool with Fortune for gravel and leaves
	alwaysPreferFortune = false
	# 
	#AutoTools only tries to get a new tool if it is needed to break the block
	onlySwitchIfNecessary = false
	#AutoTools will switch back to you previous tool or item you had in your hand before breaking the block
	switchBack = false
	#Displays the weapons Dps when hovering over it.
	showDPS = true
	#AutoTools won't change to a better weapon(e.g. a sword) when holding an axe
	changeForEntities = false
	# 
	#Autotools will prefer Silk Touch: never, always, always_ores, except_ores
	preferSilkTouch = "except_ores"
	# 
	#Add custom block-tool-configurations in JSON format
	#e.g. customTools={\"minecraft:block_id\":\"minecraft:tool_id\"} or customTools={\"minecraft:block_id\":[\"minecraft:tool_id_1\", \"minecraft:tool_id_2\"]}
	#When adding multiple tools, the first one has the highest priority
	#There are also pre-define lists for tool groups: autotools:pickaxe, autotools:axe, autotools:shovel, autotools.hoe, autotools:sword
	#eUse "autotools:disabled" to disable AutoTools on a certain block
	#Also works for entities: "minecraft:entity_id":"minecraft:tool_id
	customTools = "{}"

